//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18010.
// 
#pragma warning disable 1591

namespace DpfsLinkTestApplication.com.dpro.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DPScanServiceSoap", Namespace="http://www.dpro.com/DPScan")]
    public partial class DPScanService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CountAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShippingAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceivingAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback ItemTransferAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback ItemToProjectAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceivingValidatePOOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceivingValidateItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceivingPostReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShippingValidateSOOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShippingValidateItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShippingPostShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ItemTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback ItemToProjectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DPScanService() {
            this.Url = global::DpfsLinkTestApplication.Properties.Settings.Default.DpfsLinkTestApplication_com_dpro_www_DPScanService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CountAccessCompletedEventHandler CountAccessCompleted;
        
        /// <remarks/>
        public event ShippingAccessCompletedEventHandler ShippingAccessCompleted;
        
        /// <remarks/>
        public event ReceivingAccessCompletedEventHandler ReceivingAccessCompleted;
        
        /// <remarks/>
        public event ItemTransferAccessCompletedEventHandler ItemTransferAccessCompleted;
        
        /// <remarks/>
        public event ItemToProjectAccessCompletedEventHandler ItemToProjectAccessCompleted;
        
        /// <remarks/>
        public event GetItemCompletedEventHandler GetItemCompleted;
        
        /// <remarks/>
        public event GetProjectCompletedEventHandler GetProjectCompleted;
        
        /// <remarks/>
        public event UpdateCountCompletedEventHandler UpdateCountCompleted;
        
        /// <remarks/>
        public event ReceivingValidatePOCompletedEventHandler ReceivingValidatePOCompleted;
        
        /// <remarks/>
        public event ReceivingValidateItemCompletedEventHandler ReceivingValidateItemCompleted;
        
        /// <remarks/>
        public event ReceivingPostReceiptCompletedEventHandler ReceivingPostReceiptCompleted;
        
        /// <remarks/>
        public event ShippingValidateSOCompletedEventHandler ShippingValidateSOCompleted;
        
        /// <remarks/>
        public event ShippingValidateItemCompletedEventHandler ShippingValidateItemCompleted;
        
        /// <remarks/>
        public event ShippingPostShipmentCompletedEventHandler ShippingPostShipmentCompleted;
        
        /// <remarks/>
        public event ItemTransferCompletedEventHandler ItemTransferCompleted;
        
        /// <remarks/>
        public event ItemToProjectCompletedEventHandler ItemToProjectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/CountAccess", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccessResponse CountAccess(AccessRequest aRequest) {
            object[] results = this.Invoke("CountAccess", new object[] {
                        aRequest});
            return ((AccessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CountAccessAsync(AccessRequest aRequest) {
            this.CountAccessAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void CountAccessAsync(AccessRequest aRequest, object userState) {
            if ((this.CountAccessOperationCompleted == null)) {
                this.CountAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountAccessOperationCompleted);
            }
            this.InvokeAsync("CountAccess", new object[] {
                        aRequest}, this.CountAccessOperationCompleted, userState);
        }
        
        private void OnCountAccessOperationCompleted(object arg) {
            if ((this.CountAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountAccessCompleted(this, new CountAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ShippingAccess", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccessResponse ShippingAccess(AccessRequest aRequest) {
            object[] results = this.Invoke("ShippingAccess", new object[] {
                        aRequest});
            return ((AccessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ShippingAccessAsync(AccessRequest aRequest) {
            this.ShippingAccessAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ShippingAccessAsync(AccessRequest aRequest, object userState) {
            if ((this.ShippingAccessOperationCompleted == null)) {
                this.ShippingAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShippingAccessOperationCompleted);
            }
            this.InvokeAsync("ShippingAccess", new object[] {
                        aRequest}, this.ShippingAccessOperationCompleted, userState);
        }
        
        private void OnShippingAccessOperationCompleted(object arg) {
            if ((this.ShippingAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShippingAccessCompleted(this, new ShippingAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ReceivingAccess", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccessResponse ReceivingAccess(AccessRequest aRequest) {
            object[] results = this.Invoke("ReceivingAccess", new object[] {
                        aRequest});
            return ((AccessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceivingAccessAsync(AccessRequest aRequest) {
            this.ReceivingAccessAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ReceivingAccessAsync(AccessRequest aRequest, object userState) {
            if ((this.ReceivingAccessOperationCompleted == null)) {
                this.ReceivingAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceivingAccessOperationCompleted);
            }
            this.InvokeAsync("ReceivingAccess", new object[] {
                        aRequest}, this.ReceivingAccessOperationCompleted, userState);
        }
        
        private void OnReceivingAccessOperationCompleted(object arg) {
            if ((this.ReceivingAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceivingAccessCompleted(this, new ReceivingAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ItemTransferAccess", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccessResponse ItemTransferAccess(AccessRequest aRequest) {
            object[] results = this.Invoke("ItemTransferAccess", new object[] {
                        aRequest});
            return ((AccessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ItemTransferAccessAsync(AccessRequest aRequest) {
            this.ItemTransferAccessAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ItemTransferAccessAsync(AccessRequest aRequest, object userState) {
            if ((this.ItemTransferAccessOperationCompleted == null)) {
                this.ItemTransferAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItemTransferAccessOperationCompleted);
            }
            this.InvokeAsync("ItemTransferAccess", new object[] {
                        aRequest}, this.ItemTransferAccessOperationCompleted, userState);
        }
        
        private void OnItemTransferAccessOperationCompleted(object arg) {
            if ((this.ItemTransferAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ItemTransferAccessCompleted(this, new ItemTransferAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ItemToProjectAccess", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccessResponse ItemToProjectAccess(AccessRequest aRequest) {
            object[] results = this.Invoke("ItemToProjectAccess", new object[] {
                        aRequest});
            return ((AccessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ItemToProjectAccessAsync(AccessRequest aRequest) {
            this.ItemToProjectAccessAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ItemToProjectAccessAsync(AccessRequest aRequest, object userState) {
            if ((this.ItemToProjectAccessOperationCompleted == null)) {
                this.ItemToProjectAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItemToProjectAccessOperationCompleted);
            }
            this.InvokeAsync("ItemToProjectAccess", new object[] {
                        aRequest}, this.ItemToProjectAccessOperationCompleted, userState);
        }
        
        private void OnItemToProjectAccessOperationCompleted(object arg) {
            if ((this.ItemToProjectAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ItemToProjectAccessCompleted(this, new ItemToProjectAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/GetItem", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse GetItem(ItemRequest aRequest) {
            object[] results = this.Invoke("GetItem", new object[] {
                        aRequest});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemAsync(ItemRequest aRequest) {
            this.GetItemAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void GetItemAsync(ItemRequest aRequest, object userState) {
            if ((this.GetItemOperationCompleted == null)) {
                this.GetItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemOperationCompleted);
            }
            this.InvokeAsync("GetItem", new object[] {
                        aRequest}, this.GetItemOperationCompleted, userState);
        }
        
        private void OnGetItemOperationCompleted(object arg) {
            if ((this.GetItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemCompleted(this, new GetItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/GetProject", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProjectResponse GetProject(ProjectRequest aRequest) {
            object[] results = this.Invoke("GetProject", new object[] {
                        aRequest});
            return ((ProjectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectAsync(ProjectRequest aRequest) {
            this.GetProjectAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void GetProjectAsync(ProjectRequest aRequest, object userState) {
            if ((this.GetProjectOperationCompleted == null)) {
                this.GetProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectOperationCompleted);
            }
            this.InvokeAsync("GetProject", new object[] {
                        aRequest}, this.GetProjectOperationCompleted, userState);
        }
        
        private void OnGetProjectOperationCompleted(object arg) {
            if ((this.GetProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectCompleted(this, new GetProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/UpdateCount", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateCountResponse UpdateCount(UpdateCountRequest aRequest) {
            object[] results = this.Invoke("UpdateCount", new object[] {
                        aRequest});
            return ((UpdateCountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCountAsync(UpdateCountRequest aRequest) {
            this.UpdateCountAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void UpdateCountAsync(UpdateCountRequest aRequest, object userState) {
            if ((this.UpdateCountOperationCompleted == null)) {
                this.UpdateCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCountOperationCompleted);
            }
            this.InvokeAsync("UpdateCount", new object[] {
                        aRequest}, this.UpdateCountOperationCompleted, userState);
        }
        
        private void OnUpdateCountOperationCompleted(object arg) {
            if ((this.UpdateCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCountCompleted(this, new UpdateCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ReceivingValidatePO", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivingValidatePOResponse ReceivingValidatePO(ReceivingValidatePORequest aRequest) {
            object[] results = this.Invoke("ReceivingValidatePO", new object[] {
                        aRequest});
            return ((ReceivingValidatePOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceivingValidatePOAsync(ReceivingValidatePORequest aRequest) {
            this.ReceivingValidatePOAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ReceivingValidatePOAsync(ReceivingValidatePORequest aRequest, object userState) {
            if ((this.ReceivingValidatePOOperationCompleted == null)) {
                this.ReceivingValidatePOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceivingValidatePOOperationCompleted);
            }
            this.InvokeAsync("ReceivingValidatePO", new object[] {
                        aRequest}, this.ReceivingValidatePOOperationCompleted, userState);
        }
        
        private void OnReceivingValidatePOOperationCompleted(object arg) {
            if ((this.ReceivingValidatePOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceivingValidatePOCompleted(this, new ReceivingValidatePOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ReceivingValidateItem", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivingValidateItemResponse ReceivingValidateItem(ReceivingValidateItemRequest aRequest) {
            object[] results = this.Invoke("ReceivingValidateItem", new object[] {
                        aRequest});
            return ((ReceivingValidateItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceivingValidateItemAsync(ReceivingValidateItemRequest aRequest) {
            this.ReceivingValidateItemAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ReceivingValidateItemAsync(ReceivingValidateItemRequest aRequest, object userState) {
            if ((this.ReceivingValidateItemOperationCompleted == null)) {
                this.ReceivingValidateItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceivingValidateItemOperationCompleted);
            }
            this.InvokeAsync("ReceivingValidateItem", new object[] {
                        aRequest}, this.ReceivingValidateItemOperationCompleted, userState);
        }
        
        private void OnReceivingValidateItemOperationCompleted(object arg) {
            if ((this.ReceivingValidateItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceivingValidateItemCompleted(this, new ReceivingValidateItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ReceivingPostReceipt", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivingPostReceiptResponse ReceivingPostReceipt(ReceivingPostReceiptRequest aRequest) {
            object[] results = this.Invoke("ReceivingPostReceipt", new object[] {
                        aRequest});
            return ((ReceivingPostReceiptResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReceivingPostReceiptAsync(ReceivingPostReceiptRequest aRequest) {
            this.ReceivingPostReceiptAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ReceivingPostReceiptAsync(ReceivingPostReceiptRequest aRequest, object userState) {
            if ((this.ReceivingPostReceiptOperationCompleted == null)) {
                this.ReceivingPostReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceivingPostReceiptOperationCompleted);
            }
            this.InvokeAsync("ReceivingPostReceipt", new object[] {
                        aRequest}, this.ReceivingPostReceiptOperationCompleted, userState);
        }
        
        private void OnReceivingPostReceiptOperationCompleted(object arg) {
            if ((this.ReceivingPostReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceivingPostReceiptCompleted(this, new ReceivingPostReceiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ShippingValidateSO", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ShippingValidateSOResponse ShippingValidateSO(ShippingValidateSORequest aRequest) {
            object[] results = this.Invoke("ShippingValidateSO", new object[] {
                        aRequest});
            return ((ShippingValidateSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ShippingValidateSOAsync(ShippingValidateSORequest aRequest) {
            this.ShippingValidateSOAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ShippingValidateSOAsync(ShippingValidateSORequest aRequest, object userState) {
            if ((this.ShippingValidateSOOperationCompleted == null)) {
                this.ShippingValidateSOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShippingValidateSOOperationCompleted);
            }
            this.InvokeAsync("ShippingValidateSO", new object[] {
                        aRequest}, this.ShippingValidateSOOperationCompleted, userState);
        }
        
        private void OnShippingValidateSOOperationCompleted(object arg) {
            if ((this.ShippingValidateSOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShippingValidateSOCompleted(this, new ShippingValidateSOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ShippingValidateItem", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ShippingValidateItemResponse ShippingValidateItem(ShippingValidateItemRequest aRequest) {
            object[] results = this.Invoke("ShippingValidateItem", new object[] {
                        aRequest});
            return ((ShippingValidateItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ShippingValidateItemAsync(ShippingValidateItemRequest aRequest) {
            this.ShippingValidateItemAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ShippingValidateItemAsync(ShippingValidateItemRequest aRequest, object userState) {
            if ((this.ShippingValidateItemOperationCompleted == null)) {
                this.ShippingValidateItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShippingValidateItemOperationCompleted);
            }
            this.InvokeAsync("ShippingValidateItem", new object[] {
                        aRequest}, this.ShippingValidateItemOperationCompleted, userState);
        }
        
        private void OnShippingValidateItemOperationCompleted(object arg) {
            if ((this.ShippingValidateItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShippingValidateItemCompleted(this, new ShippingValidateItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ShippingPostShipment", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ShippingPostShipmentResponse ShippingPostShipment(ShippingPostShipmentRequest aRequest, string SODetailLines) {
            object[] results = this.Invoke("ShippingPostShipment", new object[] {
                        aRequest,
                        SODetailLines});
            return ((ShippingPostShipmentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ShippingPostShipmentAsync(ShippingPostShipmentRequest aRequest, string SODetailLines) {
            this.ShippingPostShipmentAsync(aRequest, SODetailLines, null);
        }
        
        /// <remarks/>
        public void ShippingPostShipmentAsync(ShippingPostShipmentRequest aRequest, string SODetailLines, object userState) {
            if ((this.ShippingPostShipmentOperationCompleted == null)) {
                this.ShippingPostShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShippingPostShipmentOperationCompleted);
            }
            this.InvokeAsync("ShippingPostShipment", new object[] {
                        aRequest,
                        SODetailLines}, this.ShippingPostShipmentOperationCompleted, userState);
        }
        
        private void OnShippingPostShipmentOperationCompleted(object arg) {
            if ((this.ShippingPostShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShippingPostShipmentCompleted(this, new ShippingPostShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ItemTransfer", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemTransferResponse ItemTransfer(ItemTransferRequest aRequest) {
            object[] results = this.Invoke("ItemTransfer", new object[] {
                        aRequest});
            return ((ItemTransferResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ItemTransferAsync(ItemTransferRequest aRequest) {
            this.ItemTransferAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ItemTransferAsync(ItemTransferRequest aRequest, object userState) {
            if ((this.ItemTransferOperationCompleted == null)) {
                this.ItemTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItemTransferOperationCompleted);
            }
            this.InvokeAsync("ItemTransfer", new object[] {
                        aRequest}, this.ItemTransferOperationCompleted, userState);
        }
        
        private void OnItemTransferOperationCompleted(object arg) {
            if ((this.ItemTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ItemTransferCompleted(this, new ItemTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dpro.com/DPScan/ItemToProject", RequestNamespace="http://www.dpro.com/DPScan", ResponseNamespace="http://www.dpro.com/DPScan", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemToProjectResponse ItemToProject(ItemToProjectRequest aRequest) {
            object[] results = this.Invoke("ItemToProject", new object[] {
                        aRequest});
            return ((ItemToProjectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ItemToProjectAsync(ItemToProjectRequest aRequest) {
            this.ItemToProjectAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void ItemToProjectAsync(ItemToProjectRequest aRequest, object userState) {
            if ((this.ItemToProjectOperationCompleted == null)) {
                this.ItemToProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItemToProjectOperationCompleted);
            }
            this.InvokeAsync("ItemToProject", new object[] {
                        aRequest}, this.ItemToProjectOperationCompleted, userState);
        }
        
        private void OnItemToProjectOperationCompleted(object arg) {
            if ((this.ItemToProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ItemToProjectCompleted(this, new ItemToProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class AccessRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ItemToProjectResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ItemToProjectRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string itemNumberField;
        
        private string projectNumberField;
        
        private double quantityField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectNumber {
            get {
                return this.projectNumberField;
            }
            set {
                this.projectNumberField = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ItemTransferResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ItemTransferRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string sourceItemNumberField;
        
        private string destinationItemNumberField;
        
        private double quantityField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string SourceItemNumber {
            get {
                return this.sourceItemNumberField;
            }
            set {
                this.sourceItemNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationItemNumber {
            get {
                return this.destinationItemNumberField;
            }
            set {
                this.destinationItemNumberField = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ShippingPostShipmentResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ShippingPostShipmentRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string salesOrderField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ShippingValidateItemResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string lineNumberField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ShippingValidateItemRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string salesOrderField;
        
        private string itemNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ShippingValidateSOResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string customerNameField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ShippingValidateSORequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string salesOrderField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ReceivingPostReceiptResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ReceivingPostReceiptRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string purchaseOrderField;
        
        private string itemNumberField;
        
        private string quantityField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                this.purchaseOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ReceivingValidateItemResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string lineNumberField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ReceivingValidateItemRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string purchaseOrderField;
        
        private string itemNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                this.purchaseOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ReceivingValidatePOResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string vendorNameField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string VendorName {
            get {
                return this.vendorNameField;
            }
            set {
                this.vendorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ReceivingValidatePORequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string purchaseOrderField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                this.purchaseOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class UpdateCountResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class UpdateCountRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string itemNumberField;
        
        private double newCountField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public double NewCount {
            get {
                return this.newCountField;
            }
            set {
                this.newCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ProjectResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string projectDescriptionField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectDescription {
            get {
                return this.projectDescriptionField;
            }
            set {
                this.projectDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ProjectRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string projectNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectNumber {
            get {
                return this.projectNumberField;
            }
            set {
                this.projectNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ItemResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string itemDescriptionField;
        
        private double currentCountField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double CurrentCount {
            get {
                return this.currentCountField;
            }
            set {
                this.currentCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class ItemRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string itemNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dpro.com/DPScan")]
    public partial class AccessResponse {
        
        private bool successField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CountAccessCompletedEventHandler(object sender, CountAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ShippingAccessCompletedEventHandler(object sender, ShippingAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShippingAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShippingAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReceivingAccessCompletedEventHandler(object sender, ReceivingAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceivingAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceivingAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ItemTransferAccessCompletedEventHandler(object sender, ItemTransferAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemTransferAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ItemTransferAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ItemToProjectAccessCompletedEventHandler(object sender, ItemToProjectAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemToProjectAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ItemToProjectAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccessResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetItemCompletedEventHandler(object sender, GetItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProjectCompletedEventHandler(object sender, GetProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateCountCompletedEventHandler(object sender, UpdateCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateCountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateCountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReceivingValidatePOCompletedEventHandler(object sender, ReceivingValidatePOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceivingValidatePOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceivingValidatePOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivingValidatePOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivingValidatePOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReceivingValidateItemCompletedEventHandler(object sender, ReceivingValidateItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceivingValidateItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceivingValidateItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivingValidateItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivingValidateItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReceivingPostReceiptCompletedEventHandler(object sender, ReceivingPostReceiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceivingPostReceiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceivingPostReceiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivingPostReceiptResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivingPostReceiptResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ShippingValidateSOCompletedEventHandler(object sender, ShippingValidateSOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShippingValidateSOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShippingValidateSOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShippingValidateSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShippingValidateSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ShippingValidateItemCompletedEventHandler(object sender, ShippingValidateItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShippingValidateItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShippingValidateItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShippingValidateItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShippingValidateItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ShippingPostShipmentCompletedEventHandler(object sender, ShippingPostShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShippingPostShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShippingPostShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShippingPostShipmentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShippingPostShipmentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ItemTransferCompletedEventHandler(object sender, ItemTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ItemTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemTransferResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemTransferResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ItemToProjectCompletedEventHandler(object sender, ItemToProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemToProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ItemToProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemToProjectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemToProjectResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591